### ISSUE TITLE
examples/game.go execution fails with go 1.5.1

### ISSUE THREAD

**Issue by ryukinix** [dradtke/go-allegro#8]
```bash
[lerax@starfox example (master)]$ pwd
/home/lerax/.go/go/src/github.com/dradtke/go-allegro/example
[lerax@starfox example (master)]$ ls
display.go  game.go  README.md  sound.go
[lerax@starfox example (master)]$ go run game.go
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/dradtke/go-allegro/allegro.(*KeyboardState).Get(0xc820016290)
	/home/lerax/.go/go/src/github.com/dradtke/go-allegro/allegro/keyboard.go:187 +0x4c
main.(*Game).Update(0xc820016280)
	/home/lerax/.go/go/src/github.com/dradtke/go-allegro/example/game.go:134 +0x35
main.main.func1()
	/home/lerax/.go/go/src/github.com/dradtke/go-allegro/example/game.go:255 +0xc8c
github.com/dradtke/go-allegro/allegro.go_main()
	/home/lerax/.go/go/src/github.com/dradtke/go-allegro/allegro/main.go:14 +0x75
github.com/dradtke/go-allegro/allegro._Cfunc_run_main()
	??:0 +0x31
github.com/dradtke/go-allegro/allegro.Run(0x592ad8)
	/home/lerax/.go/go/src/github.com/dradtke/go-allegro/allegro/main.go:32 +0x2d
main.main()
	/home/lerax/.go/go/src/github.com/dradtke/go-allegro/example/game.go:260 +0x23
exit status 2
```

**Comment by dradtke** [comment]
I wasn't able to reproduce this with 1.5.1, but I did run into this using 1.6rc2, and it looks like it's caused by new checks regarding cgo usage: https://github.com/golang/go/issues/12416

I'm not sure what the fix is yet, but a workaround is to run the example as:

```
$ GODEBUG=cgocheck=0 go run game.go
```

to disable the checks.

**Comment by ryukinix** [comment]
Great workaround, works fine!
